export { supabase } from "../../shared/supabase-client.js";

export {
  cleanDisplayName,
  normalizeAccessCode,
  normalizeConfigName,
  normalizeModuleKey,
  normalizeActivityConfigMeta,
  sanitizeActivityConfigJson,
  mergeActivityDashboardMeta,
  mergePreservedActivityMeta,
  normalizeFolderRecord,
  sortActivitiesByDashboardMeta,
  sortFoldersByMeta,
  withActivityDashboardMeta
} from "../../shared/api-common.js";

export {
  getCurrentUser,
  signInUser,
  signOutUser,
  getCurrentSession,
  getMyTeacherSpace,
  createMyTeacherSpace,
  createOrGetMyTeacherSpace,
  updateMyTeacherSpace,
  markTeacherSpaceAsOpened,
  getMyTeacherClasses,
  createTeacherClass,
  updateTeacherClass,
  deleteTeacherClass,
  listTeacherVocabularyWords,
  replaceTeacherVocabularyWords,
  resetTeacherVocabularyWords,
  listTeacherPhonologyPresets,
  upsertTeacherPhonologyPreset,
  deleteTeacherPhonologyPreset,
  getMyActivitiesForSpace,
  getMyActivityFoldersForSpace,
  createActivityFolderForSpace,
  updateActivityFolder,
  deleteActivityFolder,
  getMyActivityByName,
  saveActivityConfig,
  deleteMyActivity,
  updateActivityDashboardMeta,
  saveActivityOrderForTeacherSpace,
  setHighlightedActivityForTeacherSpace,
  listStudentsForClass,
  listStudentStorageContainersForSpace,
  ensureDefaultStudentStorageContainerForSpace,
  listStudentsForTeacherSpace,
  listStudentsForSpace,
  createStudent,
  createStudentForTeacherSpace,
  updateStudent,
  deleteStudent,
  saveStudentOrderForTeacherSpace,
  replaceStudentsForClass
} from "./teacher-api.js";

export {
  accessCodeExists,
  listPublicActivitiesForSpace,
  listPublicImageAssets,
  getPublicImageAssetUrl,
  listPublicPhonologyWords,
  listPublicActivityFoldersForSpace,
  listPublicClassesForSpace,
  listPublicStudentsForSpace,
  listPublicVocabularyWordsForSpace,
  loadPublicActivityConfig
} from "../../shared/public-api.js";
