-- =========================================================
-- PATCH 03 — Missions
-- Version patchable.
-- =========================================================

-- Pour l’instant, utiliser le fichier complet :
--   sql/from_scratch/03_missions.sql
--
-- Raison : la création de Missions est le cœur du prochain gros patch et doit
-- être synchronisée avec le remplacement côté front de l’ancien couple :
--   activity_configs + activity_folders
-- par :
--   mission_folders + missions + mission_steps + mission_assignments
--
-- À ne pas appliquer seul si le front n’a pas encore été patché.
