import { getCurrentUser, getMyTeacherSpace, listTeacherActivitiesForSpace } from "../../teacher/js/teacher-api.js";
import { createSessionEngine } from "../../shared/student-core.js";
import { createSessionShell } from "../../student/views/session-shell.js";
import { normalizeCatalogActivity, buildCatalogActivityConfig } from "../../shared/catalogue.js";
import { createShuttleMotion } from "./shuttle-motion.js?v=13";
(function(){
'use strict';
const E=window.FuseeEngine,KEYS=E.KEYS,COLORS=['#fc875c','#8ed96b','#f47eb6','#bc97ff','#65dfe5','#ffc65b','#82a9ff','#f6eee0'];
const RES={carburant:{name:'Carburant',icon:'carburant.png',code:'car'},eau:{name:'Eau',icon:'eau.png',code:'eau'},provisions:{name:'Provisions',icon:'provisions.png',code:'pro'},outils:{name:'Outils',icon:'outils.png',code:'out'},oxygene:{name:'Oxygène',icon:'oxygen.png',code:'oxy'}};
const CONFIG_KEY='fusee.tujer.config.v2',GAME_KEY='fusee.tujer.game.v2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=value=>JSON.parse(JSON.stringify(value??null));
function withDe(value){const word=String(value??'').trim(),initial=word.normalize('NFD').replace(/\p{M}/gu,'');return (/^[aeiouyhœæ]/i.test(initial)?'d’':'de ')+word;}
const icon=k=>`<img src="media/img/${RES[k].icon}" alt="">`;
const app=document.getElementById('app');
let shuttleMotion=null,fullscreenPending=false;
let tab='mission',activityResource='carburant',game=null,paused=false,sound=true,lastTick=Date.now(),notice=null,autoTimer=null,error='',depositView=null,depositRun=null,questionRuntime=null,dieReady=false,dieTimer=null,dieShuffleTimer=null,teacherActivities=[],teacherSpace=null,checkpointSaveTimer=null;
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.style.display='none',4000);}
const stateCache=new Map();let stateDB=null;
function readLocal(key){if(stateCache.has(key))return stateCache.get(key);try{return JSON.parse(localStorage.getItem(key));}catch{return null;}}
function writeLocal(key,value){stateCache.set(key,clone(value));if(stateDB){try{const tx=stateDB.transaction('state','readwrite');tx.objectStore('state').put(JSON.stringify(value),key);tx.onerror=()=>toast('La sauvegarde est indisponible. Exporte ta préparation.');return true;}catch{}}try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{toast('La sauvegarde locale est pleine ou indisponible. Exporte ta préparation.');return false;}}
function defaults(){return {version:2,title:'Mission de ravitaillement',players:['Léa','Noah','Maya','Tom'],duration:30,dust:3,targets:Object.fromEntries(KEYS.map(k=>[k,3])),activities:Object.fromEntries(KEYS.map(k=>[k,null]))};}
let config=readLocal(CONFIG_KEY)||defaults();try{E.validate(config,true);}catch{config=defaults();}
function saveConfig(){writeLocal(CONFIG_KEY,config);}
function captureQuestionCheckpoint(){if(!game||game.phase!=='question'||!questionRuntime?.engine?.getResumeCheckpoint)return;const cp=questionRuntime.engine.getResumeCheckpoint();if(cp)game.questionCheckpoint=cp;}
function saveGame(){if(!game)return;captureQuestionCheckpoint();writeLocal(GAME_KEY,{version:2,snapshot:game.snapshot(),notice});}
const EFFECTS={dice:'media/sons/jeu/roll.wav',shuttle:'media/sons/jeu/navette.flac',collect:'media/sons/jeu/collect.wav'},effectAudio=new Map(),imageCache=new Map();
let assetsReady=false,assetPreparation=null,assetGeneration=0;
function stopAudio(){for(const audio of effectAudio.values()){audio.pause();try{audio.currentTime=0;}catch{}}}
function playEffect(name){if(!sound||paused||document.hidden)return;let audio=effectAudio.get(name);if(!audio){audio=new Audio(EFFECTS[name]);audio.preload='auto';effectAudio.set(name,audio);}if(name!=='collect'&&!audio.paused&&!audio.ended)return;try{audio.currentTime=0;}catch{}audio.play()?.catch(()=>{});}
// Compter les ressources portées et déposées évite de sonoriser un simple transfert.
function resourceTotal(){return KEYS.reduce((total,k)=>total+game.stock[k]+game.players.reduce((sum,p)=>sum+p.bag[k],0),game.dust);}
function withCollectionSound(change){const before=resourceTotal(),result=change();if(resourceTotal()>before)playEffect('collect');return result;}
function preloadImage(src){if(imageCache.has(src))return imageCache.get(src).ready;const img=new Image(),entry={img,ready:null};entry.ready=new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(timeout);img.onload=null;img.onerror=null;resolve();},timeout=setTimeout(finish,12000);img.onload=()=>{if(img.decode)img.decode().then(finish,finish);else finish();};img.onerror=finish;img.src=src;});imageCache.set(src,entry);return entry.ready;}
function prepareAssets(){const sources=new Set(['media/img/fond-plateau.jpg','plateau-original.jpg','media/img/rocket-off.svg','media/img/Navette.webp?v=12','media/img/Rocket70.png','media/img/evenement.png',...KEYS.map(k=>'media/img/'+RES[k].icon),...KEYS.flatMap(k=>['media/events/P_'+RES[k].code+'.png','media/events/M_'+RES[k].code+'.png'])]);const generation=++assetGeneration;for(const [name,src] of Object.entries(EFFECTS))if(!effectAudio.has(name)){const audio=new Audio(src);audio.preload='auto';audio.load?.();effectAudio.set(name,audio);}if(typeof Image==='undefined'){assetsReady=true;return null;}assetsReady=false;assetPreparation=Promise.all([...sources].map(preloadImage)).then(()=>{if(generation===assetGeneration)assetsReady=true;});return assetPreparation;}
function stopDieAnimation(){clearTimeout(dieTimer);clearTimeout(dieShuffleTimer);}
function download(name,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
function button(text,action,classes='',extra=''){return `<button class="${classes}" data-action="${action}" ${extra}>${text}</button>`;}
function destroyQuestionRuntime(){if(!questionRuntime)return;captureQuestionCheckpoint();questionRuntime.disposed=true;try{questionRuntime.engine?.stop?.({attemptStatus:'interrupted'});}catch{}questionRuntime.abort?.abort?.();questionRuntime=null;clearTimeout(checkpointSaveTimer);}
function modal(content,classes=''){destroyQuestionRuntime();const old=document.querySelector('.modal-backdrop');if(old)old.remove();const el=document.createElement('div');el.className='modal-backdrop'+(/resource-modal|deposit-modal|dice-modal/.test(classes)?' clear-backdrop':'')+(/question-modal/.test(classes)?' question-backdrop':'')+(/mission-gate/.test(classes)?' mission-gate-backdrop':'')+(/dice-modal/.test(classes)?' dice-backdrop':'');el.innerHTML=`<section class="modal ${classes}" role="dialog" aria-modal="true" aria-label="${game?'Mission':'Préparation'}">${content}</section>`;document.body.append(el);const first=el.querySelector('button,input,select,textarea');first?.focus({preventScroll:true});}
function closeModal(){destroyQuestionRuntime();document.querySelector('.modal-backdrop')?.remove();}
function showMissionGate(){paused=true;const selected=game,pending=prepareAssets();modal(button(assetsReady?'Démarrer la mission':'Chargement de la mission…','launch-mission','primary',assetsReady?'':'disabled'),'mission-gate centered');pending?.then(()=>{if(game!==selected||game.missionStarted!==false||!assetsReady)return;const el=document.querySelector('[data-action="launch-mission"]');if(el){el.textContent='Démarrer la mission';el.disabled=false;}});}
function enterFullscreen(){if(document.fullscreenElement||fullscreenPending||!document.documentElement.requestFullscreen)return;try{fullscreenPending=true;Promise.resolve(document.documentElement.requestFullscreen()).catch(()=>{}).finally(()=>{fullscreenPending=false;});}catch{fullscreenPending=false;}}
function restoreGameFullscreen(){if(game&&game.missionStarted!==false)enterFullscreen();}
function launchMission(){if(!game||!assetsReady)return;enterFullscreen();game.missionStarted=true;paused=false;lastTick=Date.now();closeModal();renderGame();if(!notice&&game.phase==='roll')notice={type:'next',player:game.active};showPhase();saveGame();}
function setup(){shuttleMotion?.destroy();shuttleMotion=null;document.body.classList.remove('game-mode');clearTimeout(autoTimer);stopDieAnimation();closeModal();app.innerHTML=`<main class="setup"><header class="setup-header"><div class="brand"><img src="media/img/Rocket70.png" alt=""><div><p class="eyebrow">Jeu coopératif · Tujer</p><strong>La Fusée</strong></div></div><div class="toolbar">${readLocal(GAME_KEY)?button('Reprendre la partie','resume','secondary'):''}${button('Exporter la préparation','export','secondary small')}<label class="file-label">Importer<input type="file" accept=".json" data-file="config"></label></div></header><nav class="tabs" aria-label="Préparation">${button('La mission','tab-mission','',`role="tab" aria-selected="${tab==='mission'}"`)}${button('Les activités','tab-activities','',`role="tab" aria-selected="${tab==='activities'}"`)}</nav>${error?`<p role="alert" class="error">${esc(error)}</p>`:''}${tab==='mission'?missionSetup():activitiesSetup()}<footer class="setup-footer"><span class="muted" id="mission-summary">${config.players.length} astronautes · ${KEYS.reduce((s,k)=>s+config.targets[k],0)} ressources à déposer</span>${button('Commencer la mission','start','primary')}</footer></main>`;if(tab==='mission')drawMini();}
function missionSetup(){return `<div class="setup-grid"><section class="panel crew-panel"><div class="inline"><h2>L’équipage</h2><label>Joueurs <select id="player-count">${[2,3,4,5,6,7,8].map(n=>`<option ${n===config.players.length?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="crew-inputs">${config.players.map((name,i)=>`<label class="crew-field"><span class="color-dot" style="background:${COLORS[i]}"></span><input aria-label="Prénom du joueur ${i+1}" data-player="${i}" maxlength="24" value="${esc(name)}"></label>`).join('')}</div></section><section class="panel mission-panel"><h2>La mission</h2><label class="field">Nom de la mission<input id="mission-title" maxlength="60" value="${esc(config.title)}"></label><div class="inline"><label class="field">Durée cible (minutes)<input id="duration" type="number" min="5" max="120" value="${config.duration}"></label><label class="field">Poussière d’étoile au départ<input id="dust" type="number" min="0" max="30" value="${config.dust}"></label></div><p class="helptext">Le jeu ajuste discrètement les événements pour se rapprocher de cette durée. Les élèves ne voient pas le chronomètre. Une poussière permet d’appeler un camarade pendant une question.</p></section><div class="setup-preview"><section class="panel preview-panel"><div id="mini-board" class="mini-board"></div><p class="preview-caption">${config.players.length} planètes · un seul équipage</p></section><section class="panel"><h2>À déposer dans la fusée</h2><div class="targets">${KEYS.map(k=>`<div class="target">${icon(k)}<label for="target-${k}">${RES[k].name}</label><input id="target-${k}" data-target="${k}" type="number" min="0" max="50" value="${config.targets[k]}"></div>`).join('')}</div></section></div></div>`;}
function isRunnableActivity(activity){return !!String(activity?.config_json?.tool_id||'').trim();}
function activityTypeLabel(activity){return activity?.activity_type==='series'?'Série':activity?.activity_type==='quiz'?'Quiz':'Activité';}
function activitiesSetup(){const assignment=config.activities?.[activityResource]||null;const usable=teacherActivities.filter(isRunnableActivity);return `<div class="question-layout activity-layout"><aside class="activity-nav">${KEYS.map(k=>{const a=config.activities?.[k];return button(`${icon(k)}<span>${RES[k].name}<small>${a?esc(a.title):'Non configurée'}</small></span>`,'activity-'+k,k===activityResource?'active':'');}).join('')}</aside><section class="panel activity-config-panel"><div class="activity-header"><div><p class="eyebrow">Activité Tujer</p><h2>${RES[activityResource].name}</h2></div></div><p class="helptext">Choisis l’activité qui sera lancée quand cette ressource est sélectionnée. Une question est lancée à chaque fois, à partir d’un outil génératif, d’un quiz ou d’une série.</p>${usable.length?`<label class="field">Activité<select id="activity-select" data-resource="${activityResource}"><option value="">— Choisir une activité —</option>${usable.map(a=>`<option value="${esc(a.id)}" ${String(assignment?.id||'')===String(a.id)?'selected':''}>${esc(a.title)} · ${activityTypeLabel(a)}</option>`).join('')}</select></label>`:`<div class="activity-empty"><strong>Aucune activité utilisable.</strong><p>Crée d’abord une activité, un quiz ou une série dans « Mes activités ».</p><a class="secondary activity-link" href="../../teacher/dashboard.html">Retour à Tujer</a></div>`}${assignment?`<label class="field activity-level-field">Niveau de départ<select id="activity-level" data-resource="${activityResource}" ${assignment.snapshot?.difficulty_mode==='adaptive'?'':'disabled'}>${[1,2,3,4,5].map(n=>`<option value="${n}" ${Number(assignment.level||3)===n?'selected':''}>Niveau ${n}</option>`).join('')}</select><small class="helptext">${assignment.snapshot?.difficulty_mode==='adaptive'?'Niveau utilisé au lancement de chaque question.':'Cette activité utilise une configuration unique.'}</small></label><div class="selected-activity-card"><strong>${esc(assignment.title)}</strong><span>${activityTypeLabel(assignment.snapshot)} · ${esc(assignment.snapshot?.config_json?.tool_id||'')}</span></div>`:''}</section></div>`;}
function drawMini(){const b=E.board(config.players.length),el=document.getElementById('mini-board');let html='<svg viewBox="0 0 100 100" preserveAspectRatio="none" class="board-lines">'+b.edges.map(([a,c])=>`<line x1="${b.nodes[a].x}" y1="${b.nodes[a].y}" x2="${b.nodes[c].x}" y2="${b.nodes[c].y}"/>`).join('')+'</svg>';for(const node of Object.values(b.nodes)){html+=`<div style="position:absolute;left:${node.x}%;top:${node.y}%;transform:translate(-50%,-50%);width:${node.type==='planet'?30:node.type==='center'?26:10}px;height:${node.type==='planet'?30:node.type==='center'?36:10}px;border-radius:50%;background:${node.type==='planet'?COLORS[node.owner]:'#ffc24b'}">${node.type==='center'?'<img src="media/img/Rocket70.png" style="width:100%;height:100%;object-fit:contain" alt="">':''}</div>`;}el.innerHTML=html;}
function start(){error='';refreshActivitySnapshots(false);try{E.validate(config);}catch(e){error=e.message;setup();return;}const begin=()=>{saveConfig();game=new E.Game(config);game.active=Math.floor(Math.random()*game.players.length);lastTick=Date.now();paused=true;game.missionStarted=false;notice={type:'next',player:game.active};closeModal();renderGame();showMissionGate();saveGame();};if(readLocal(GAME_KEY))modal(`<h2>Commencer une nouvelle partie ?</h2><p>La partie enregistrée sera remplacée. Ta préparation est conservée.</p><div class="modal-actions">${button('Annuler','close','secondary')}${button('Nouvelle partie','confirm-start','primary')}</div>`);else begin();start.begin=begin;}
function dieFace(){if(game.phase==='die'&&!dieReady)return '<small>…</small>';return game.die==='rocket'?'<img src="media/img/Rocket70.png" alt="Fusée">':game.die==='asteroid'?'<img src="media/img/evenement.png" alt="Astéroïde">':esc(game.die??'·');}
function renderGame(){if(!game)return;const existingBoard=document.getElementById('board');document.body.classList.add('game-mode');const p=game.players[game.active],stock=depositView?.stock||game.stock,bags=depositView?.bags||game.players.map(p=>p.bag);app.innerHTML=`<main class="game"><header class="game-header"><div class="brand"><img src="media/img/rocket-off.svg" alt=""><strong>La Fusée</strong></div><div class="mission-gauges" aria-label="Ressources déposées dans la fusée">${KEYS.map(k=>`<div class="gauge" id="gauge-${k}" role="group" aria-label="${RES[k].name}">${icon(k)}<div class="track" role="progressbar" aria-label="${RES[k].name}" aria-valuemin="0" aria-valuemax="${config.targets[k]}" aria-valuenow="${Math.min(stock[k],config.targets[k])}"><i style="width:${config.targets[k]?Math.min(100,stock[k]/config.targets[k]*100):100}%"></i></div><b>${Math.min(stock[k],config.targets[k])}/${config.targets[k]}</b></div>`).join('')}<div class="dust-divider" aria-hidden="true"></div><div class="dust" aria-label="${game.dust} poussières d’étoile">✨ <b>${game.dust}</b></div></div><div class="toolbar">${button(sound?'♫':'♫̸','sound','small secondary',`aria-label="${sound?'Couper':'Activer'} le son"`)}${button('⛶','fullscreen','small secondary','aria-label="Plein écran"')}${button('Ⅱ','pause','small secondary','aria-label="Pause et options enseignant"')}</div></header><div class="game-main"><section class="space" aria-label="Plateau de jeu"><div class="board" id="board"></div>${depositView?'<div class="deposit-banner" role="status">Ravitaillement de la fusée…</div>':''}</section></div><footer class="game-footer" aria-label="Tour de jeu et ressources portées"><div class="turn-panel"><button class="die" data-action="roll" aria-label="${game.phase==='roll'?'Lancer le dé':game.phase==='die'&&!dieReady?'Lancer en cours':game.die==='rocket'?'Fusée':game.die==='asteroid'?'Astéroïde':'Résultat du dé : '+(game.die??'')}" ${game.phase!=='roll'||depositView||paused?'disabled':''}>${game.phase==='roll'?'<small>Lancer<br>le dé</small>':dieFace()}</button><strong class="active-player" title="${esc(p.name)}" style="color:${COLORS[game.active]}">${esc(p.name)}</strong><span class="sr-only" aria-live="polite">${game.phase==='move'?'Touche une case éclairée et compte tes déplacements.':''}</span></div><div class="crew-bags">${game.players.map((p,i)=>`<article class="crew-card ${i===game.active?'active':''}" style="--player:${COLORS[i]}"><strong>${esc(p.name)}</strong><div class="bag">${KEYS.map(k=>`<span class="bag-item" id="bag-${i}-${k}" title="${RES[k].name}">${icon(k)}<b>${bags[i][k]}</b></span>`).join('')}</div></article>`).join('')}</div></footer></main>`;if(existingBoard)document.getElementById('board').replaceWith(existingBoard);renderBoard();}

function layoutBoard(b,width,height){const key=`v3:${width}x${height}`;if(game.layout?.key!==key)game.layout={key,points:E.createLayout(game.players.length,game.layoutSeed,width,height)};for(const [id,point] of Object.entries(game.layout.points))Object.assign(b.nodes[id],point);}
function renderBoard(){const el=document.getElementById('board');if(!el)return;const b=game.board,options=game.options(),previousLayout=game.layout?.key;layoutBoard(b,el.clientWidth||1000,el.clientHeight||560);let layer=el.querySelector('.board-nodes');if(!layer){el.innerHTML='<div class="board-nodes"></div><div class="shuttle"><img src="media/img/Navette.webp?v=12" alt="Navette commune"></div>';layer=el.querySelector('.board-nodes');}layer.innerHTML=`<svg class="board-lines" viewBox="0 0 100 100" preserveAspectRatio="none">${b.edges.map(([a,c])=>`<line x1="${b.nodes[a].x}" y1="${b.nodes[a].y}" x2="${b.nodes[c].x}" y2="${b.nodes[c].y}"/>`).join('')}</svg>`+Object.values(b.nodes).map(n=>`<button class="node ${n.type} ${options.includes(n.id)?'available':''} ${game.blocked[n.id]?'blocked':''}" style="left:${n.x}%;top:${n.y}%;${n.type==='planet'?'--player:'+COLORS[n.owner]:''}" data-action="move" data-node="${n.id}" ${!options.includes(n.id)?'disabled':''} aria-label="${n.type==='planet'?'Planète '+esc(withDe(game.players[n.owner].name)):n.type==='asteroid'?'Astéroïde':n.type==='center'?'Fusée centrale':'Case de déplacement'}">${n.type==='planet'?`<span class="planet-art art${n.owner%4}"></span><span class="planet-name">${esc(game.players[n.owner].name)}</span>${game.blocked[n.id]?'<span class="closed-symbol">⛔</span>':''}`:n.type==='asteroid'?'<img src="media/img/evenement.png" alt="">':n.type==='center'?'<img class="central-rocket" src="media/img/rocket-off.svg" alt="">':''}</button>`).join('');const shuttle=el.querySelector('.shuttle');if(shuttleMotion?.element!==shuttle||shuttleMotion?.game!==game){shuttleMotion?.destroy();shuttleMotion=createShuttleMotion(shuttle);shuttleMotion.element=shuttle;shuttleMotion.game=game;}shuttleMotion.setPaused(paused);shuttle.classList.toggle('docked',game.position==='c');const point=b.nodes[game.position];shuttleMotion.moveTo({x:point.x*(el.clientWidth||1000)/100+(game.position==='c'?24:0),y:point.y*(el.clientHeight||560)/100},{instant:previousLayout!==game.layout?.key});}

function scheduleArrival(){const selected=game;(shuttleMotion?.whenIdle()||Promise.resolve()).then(()=>{if(game===selected&&!paused&&game?.phase==='arrive')resolveArrival();});}
function resolveArrival(){if(!game||paused||game.phase!=='arrive')return;const before={stock:{...game.stock},bags:game.players.map(p=>({...p.bag}))};const result=withCollectionSound(()=>game.resolve());notice=result;saveGame();if((result.type==='deposit'||result.type==='won')&&KEYS.some(k=>result.deposited[k]>0)){animateDeposit(before);return;}renderGame();if(result.type==='planet'){showResources();return;}showNotice();}
function updateDepositCounters(){if(!depositView)return;for(const k of KEYS){const gauge=document.getElementById('gauge-'+k),track=gauge?.querySelector('.track'),fill=gauge?.querySelector('i'),count=gauge?.querySelector('b');const amount=Math.min(depositView.stock[k],config.targets[k]);if(track)track.setAttribute('aria-valuenow',amount);if(fill)fill.style.width=(config.targets[k]?Math.min(100,amount/config.targets[k]*100):100)+'%';if(count)count.textContent=amount+'/'+config.targets[k];}depositView.bags.forEach((bag,i)=>KEYS.forEach(k=>{const count=document.getElementById(`bag-${i}-${k}`)?.querySelector('b');if(count)count.textContent=bag[k];}));}
function finishDeposit(show=true){const run=depositRun;if(run){run.cancelled=true;run.timers.forEach(clearTimeout);run.flights.forEach(el=>el.remove());}depositRun=null;depositView=null;renderGame();if(show&&!paused)showNotice();}
function animateDeposit(before){closeModal();depositView=before;renderGame();const jobs=[];before.bags.forEach((bag,player)=>KEYS.forEach(k=>{if(bag[k]>0)jobs.push({player,k,amount:bag[k]});}));const first=document.getElementById(`bag-${jobs[0].player}-${jobs[0].k}`);if(!first?.getBoundingClientRect){finishDeposit();return;}
 const duration=2000,run=depositRun={cancelled:false,timers:[],flights:[],pending:jobs.length};
 jobs.forEach((job,index)=>{run.timers.push(setTimeout(()=>{if(run.cancelled)return;const sourceEl=document.getElementById(`bag-${job.player}-${job.k}`),targetEl=document.getElementById('gauge-'+job.k),source=sourceEl.getBoundingClientRect(),target=targetEl.getBoundingClientRect(),flight=document.createElement('div');flight.className='resource-flight';flight.innerHTML=icon(job.k)+`<b>×${job.amount}</b>`;flight.style.left=(source.left+source.width/2-34)+'px';flight.style.top=(source.top+source.height/2-34)+'px';flight.style.setProperty('--flight-x',(target.left+target.width/2-source.left-source.width/2)+'px');flight.style.setProperty('--flight-y',(target.top+target.height/2-source.top-source.height/2)+'px');flight.style.setProperty('--flight-duration',duration+'ms');document.body.append(flight);run.flights.push(flight);sourceEl.classList.add('bag-departure');run.timers.push(setTimeout(()=>{if(run.cancelled)return;flight.remove();sourceEl.classList.remove('bag-departure');targetEl.classList.add('gauge-arrival');depositView.bags[job.player][job.k]=0;depositView.stock[job.k]+=job.amount;updateDepositCounters();if(--run.pending===0)run.timers.push(setTimeout(()=>{if(!run.cancelled)finishDeposit();},450));},duration));},250+index*Math.min(260,2600/Math.max(1,jobs.length-1))));});
}
const DIE_ROTATIONS={rocket:[0,0],2:[0,-90],3:[0,90],4:[-90,0],5:[90,0],asteroid:[0,180]};
function cubeFace(face){return face==='rocket'?'<img class="die-rocket" src="media/img/rocket-off.svg" alt="">':face==='asteroid'?'<img src="media/img/evenement.png" alt="">':String(face);}
function showDie(animate=false){stopDieAnimation();dieReady=!animate;renderGame();const [x,y]=DIE_ROTATIONS[game.die],label=game.die==='rocket'?'Fusée':game.die==='asteroid'?'Astéroïde':String(game.die);modal(`<button type="button" id="die-confirm" class="rolling-die ${animate?'is-rolling':'is-ready'}" data-action="accept-die" aria-label="Dé : ${animate?'lancer en cours':label+'. Touche le dé pour valider.'}" ${animate?'disabled':''} style="--die-x:${x}deg;--die-y:${y}deg"><span class="die-cube">${E.DIE_FACES.map((face,i)=>`<span class="die-face face-${i}">${cubeFace(face)}</span>`).join('')}</span>${animate?'<span class="die-shuffle" aria-hidden="true"></span>':''}</button>`,'dice-modal');if(animate){playEffect('dice');const digit=document.querySelector('.die-shuffle');let previous=null,step=0,pool=[];const shuffle=()=>{if(paused||!game||game.phase!=='die'||!digit?.parentElement)return;if(!pool.length)pool=[...E.DIE_FACES];const faces=pool.filter(f=>f!==previous),face=faces[Math.floor(Math.random()*faces.length)];pool.splice(pool.indexOf(face),1);previous=face;digit.dataset.face=String(face);digit.innerHTML=cubeFace(face);dieShuffleTimer=setTimeout(shuffle,Math.min(90,50+step++*2));};shuffle();dieTimer=setTimeout(()=>{clearTimeout(dieShuffleTimer);if(paused||!game||game.phase!=='die')return;dieReady=true;const el=document.getElementById('die-confirm');digit?.remove();el.disabled=false;el.classList.remove('is-rolling');el.classList.add('is-ready');el.setAttribute('aria-label',`Dé : ${label}. Touche le dé pour valider.`);renderGame();el.focus({preventScroll:true});},1800);}}
function rollDie(){if(paused||depositView)return;if(game.phase==='notice'&&notice?.type==='next'){game.nextTurnReady=true;game.continue();}if(game.phase!=='roll')return;stopAudio();closeModal();game.roll();notice=null;saveGame();showDie(true);}
function acceptDie(){if(paused||!dieReady||game.phase!=='die')return;dieReady=false;closeModal();const previous=game.position;game.acceptRoll();renderGame();if(game.position!==previous)playEffect('shuttle');saveGame();if(game.phase==='arrive')scheduleArrival();}
function showResources(){const p=game.players[game.active];modal(`<p class="eyebrow">Planète ${esc(withDe(p.name))}</p><h2>${esc(p.name)}, choisis une ressource</h2><div class="resource-choices">${KEYS.filter(k=>config.targets[k]>0&&config.activities?.[k]?.snapshot?.config_json?.tool_id).map(k=>button(`${icon(k)}${RES[k].name}`,'resource-'+k)).join('')}</div>`,'centered resource-modal');}

function teacherActivityRuntimeShape(activity={}){const cfg=activity?.config_json&&typeof activity.config_json==='object'&&!Array.isArray(activity.config_json)?activity.config_json:{};const adaptive=String(activity?.difficulty_mode||'single')==='adaptive';const single=cfg?.level&&typeof cfg.level==='object'&&!Array.isArray(cfg.level)?cfg.level:{};const levels=adaptive&&activity?.levels_json&&typeof activity.levels_json==='object'&&!Array.isArray(activity.levels_json)?activity.levels_json:Object.fromEntries([1,2,3,4,5].map(level=>[String(level),clone(single)]));return normalizeCatalogActivity({id:`teacher-activity.${String(activity?.id||'')}`,activity_type:String(activity?.activity_type||'tool'),config_name:String(activity?.title||'Activité'),title:String(activity?.title||'Activité'),tool_id:String(cfg?.tool_id||'').trim(),levels_json:levels,status:'published',default_visible:true});}
function buildQuestionRuntimeConfig(assignment){const runtimeActivity=teacherActivityRuntimeShape(assignment.snapshot);const runtimeConfig=buildCatalogActivityConfig(runtimeActivity,{context:'mission',difficultyLevel:Number(assignment.level)||3,adaptive:false,activityMode:'individual',responseUi:'boxed',progressMode:'practice',executionLimit:{mode:'questions',value:1}});if(!runtimeConfig?.sequence?.length)throw Error('Cette activité Tujer ne peut pas être lancée.');return runtimeConfig;}
function syncAnswerToggle(runtime){const btn=runtime?.els?.answerDisplayToggleBtn;if(!btn)return;const ui=runtime.engine?.getUiState?.()||{},visible=ui.shellAnswerToggleVisible===true,enabled=ui.shellAnswerToggleEnabled===true,label=String(ui.shellAnswerToggleLabel||'Voir ma réponse');btn.classList.toggle('hidden',!visible);btn.disabled=!visible||!enabled;btn.title=label;btn.setAttribute('aria-label',label);btn.setAttribute('aria-hidden',visible?'false':'true');const labelEl=btn.querySelector('.session-shell-btn-label');if(labelEl)labelEl.textContent=label;}
function scheduleCheckpoint(runtime){clearTimeout(checkpointSaveTimer);checkpointSaveTimer=setTimeout(()=>{if(questionRuntime!==runtime||game?.phase!=='question')return;const cp=runtime.engine?.getResumeCheckpoint?.();if(cp){game.questionCheckpoint=cp;writeLocal(GAME_KEY,{version:2,snapshot:game.snapshot(),notice});}},120);}
function updateDustButton(runtime){const btn=runtime?.dustButton;if(!btn)return;btn.disabled=game?.helpUsed||!game?.dust;btn.title=game?.helpUsed?'Poudre déjà utilisée pour cette question':game?.dust?`${game.dust} poudre${game.dust>1?'s':''} disponible${game.dust>1?'s':''}`:'Aucune poudre disponible';}
function closeQuestionHelp(runtime){runtime?.root?.querySelector('.fusee-question-help')?.remove();}
function showQuestionHelp(runtime){if(!runtime||game?.phase!=='question'||game.helpUsed||!game.dust)return;closeQuestionHelp(runtime);const layer=document.createElement('div');layer.className='fusee-question-help';layer.innerHTML=`<div class="fusee-question-help-card"><h2>Qui viens-tu appeler ?</h2><p>Vous pourrez réfléchir ensemble à cette question.</p><div class="fusee-question-help-choices">${game.players.map((p,i)=>i===game.active?'':`<button class="btn" type="button" data-helper-index="${i}">${esc(p.name)}</button>`).join('')}</div><button class="btn" type="button" data-close-help>Annuler</button></div>`;layer.addEventListener('click',e=>{if(e.target.closest('[data-close-help]')){layer.remove();return;}const helper=e.target.closest('[data-helper-index]');if(!helper)return;const i=Number(helper.dataset.helperIndex);try{game.help(i);saveGame();updateDustButton(runtime);layer.remove();toast(`${game.players[i].name} vient aider ${game.players[game.active].name}.`);}catch(err){toast(err.message);}});runtime.root.append(layer);}
function questionShell(){modal('<div id="tujer-question-host" class="tujer-question-host"></div>','question-modal');return document.getElementById('tujer-question-host');}
async function showQuestion(){if(!game?.question?.activity)return;const root=questionShell();const assignment=game.question.activity;let runtimeConfig;try{runtimeConfig=buildQuestionRuntimeConfig(assignment);}catch(err){root.innerHTML=`<div class="fusee-runtime-error"><h2>Activité indisponible</h2><p>${esc(err.message)}</p></div>`;return;}const shell=createSessionShell(root,{currentMode:'individual',hasIndividualSidebar:false,isSharedSessionEntry:true});const els=shell.els;els.btnPause?.remove();const dustButton=document.createElement('button');dustButton.className='fusee-dust-btn';dustButton.type='button';dustButton.dataset.skipAutofs='true';dustButton.innerHTML='<span class="fusee-dust-icon" aria-hidden="true">✦</span><span>Poudre d’étoile</span>';root.append(dustButton);
const runtime={root,els,engine:null,dustButton,disposed:false,abort:new AbortController()};questionRuntime=runtime;updateDustButton(runtime);runtime.dustButton?.addEventListener('click',()=>showQuestionHelp(runtime),{signal:runtime.abort.signal});els.manualActionBtn?.addEventListener('click',()=>runtime.engine?.handleManualAction?.(),{signal:runtime.abort.signal});els.answerDisplayToggleBtn?.addEventListener('click',async()=>{await runtime.engine?.toggleShellAnswerDisplay?.();syncAnswerToggle(runtime);},{signal:runtime.abort.signal});let finishing=false;runtime.engine=createSessionEngine({els,accessCode:String(teacherSpace?.access_code||'FUSEE'),configName:String(assignment.title||'La Fusée'),moduleKey:'tools',globals:runtimeConfig.globals||{},sequence:runtimeConfig.sequence,activityMode:runtimeConfig.activity_mode||'individual',responseUi:runtimeConfig.response_ui||'boxed',progressMode:runtimeConfig.progress_mode||'practice',manualControlsEnabled:true,runMode:'student',onExitToActivities:()=>{},onFatalError:message=>{if(runtime.disposed)return;toast(message||'Erreur pendant la question.');},onStateChange:()=>{if(runtime.disposed)return;syncAnswerToggle(runtime);scheduleCheckpoint(runtime);},onSessionFinished:summary=>{if(runtime.disposed||finishing||game?.phase!=='question')return;finishing=true;const item=summary?.items?.[0]||{},correct=Number(item.correctCount||0)>0,resource=game.question.resource;queueMicrotask(async()=>{if(runtime.disposed||game?.phase!=='question')return;runtime.disposed=true;runtime.abort.abort();questionRuntime=null;clearTimeout(checkpointSaveTimer);try{await runtime.engine?.stop?.({attemptStatus:'completed'});}catch{}withCollectionSound(()=>game.resolveQuestion(correct));notice={type:'answer',correct,resource,player:game.active};renderGame();saveGame();showNotice();});}});try{await runtime.engine.init();if(runtime.disposed)return;runtime.engine.setSelectedStudent({id:`fusee-player-${game.active}`,first_name:game.players[game.active].name});await runtime.engine.startSession({resumeCheckpoint:game.questionCheckpoint||null});syncAnswerToggle(runtime);scheduleCheckpoint(runtime);}catch(err){if(!runtime.disposed){root.innerHTML=`<div class="fusee-runtime-error"><h2>Impossible de lancer l’activité</h2><p>${esc(err?.message||err)}</p></div>`;}}}

const TRANSPORT_TEXTS=[['Un raccourci spatial !','Un passage lumineux s’ouvre entre les étoiles.'],['La navette de secours','Une navette de secours vous guide jusqu’à une planète.'],['Un appel radio','Une planète vous invite à venir chercher des ressources.'],['Un courant cosmique','Un courant spatial emporte doucement votre navette.'],['Une carte retrouvée','Vous découvrez une carte montrant un chemin secret.'],['Un tunnel d’étoiles','La navette traverse un tunnel scintillant.'],['Un guide inattendu','Un petit robot vous indique une planète à explorer.'],['Une lumière au loin','Vous suivez un signal lumineux dans l’espace.'],['Un message de l’équipage','Un astronaute vous attend pour vous proposer une question.'],['Un bond spatial','Le moteur de secours vous fait sauter d’une planète à l’autre.'],['Une invitation','Les habitants d’une planète vous invitent à vous poser.'],['Une balise retrouvée','Une balise vous conduit jusqu’à un nouveau point de ravitaillement.'],['Un chemin dégagé','Une pluie de météorites révèle un passage vers une planète.'],['Une escale surprise','Le pilote automatique prépare une nouvelle escale.']];
function eventText(e){if(e.kind==='transport'){const [title,story]=TRANSPORT_TEXTS[e.story%TRANSPORT_TEXTS.length]||TRANSPORT_TEXTS[0];return {title,text:story+`<br><b>Direction la planète ${esc(withDe(game.players[e.player].name))} pour une question !</b>`,image:'media/img/Navette.webp?v=12'};}if(e.kind==='gain'||e.kind==='loss'){const r=RES[e.resource],gain=e.kind==='gain';return {title:gain?'Une trouvaille !':'Une avarie !',text:gain?`Vous récupérez une unité ${esc(withDe(r.name.toLowerCase()))}.`:`Une unité ${esc(withDe(r.name.toLowerCase()))} est perdue en route.`,image:`media/events/${gain?'P':'M'}_${r.code}.png`};}const t={dustGain:{title:'Une poussière d’étoile !',text:'Vous trouvez une nouvelle poussière d’étoile.<br><b>+1 poudre dans le sac commun.</b>'},dustLoss:{title:'Une poussière s’envole',text:'Une poussière d’étoile s’échappe par le hublot.<br><b>−1 poudre dans le sac commun.</b>'},calm:{title:'Un ciel tranquille',text:'Vous traversez le champ d’astéroïdes sans encombre. Le voyage continue.'},block:{title:'Tempête de météorites !',text:`La planète ${esc(withDe(game.players[e.player]?.name))} est fermée pendant trois lancers de dé. Les autres chemins restent ouverts.`},unblock:{title:'La tempête se dissipe',text:'Toutes les planètes sont de nouveau accessibles.'},return:{title:'Un courant vers la fusée',text:'Un courant spatial ramène la navette au centre. Déchargez vos ressources !'}};return {...t[e.kind],image:'media/img/evenement.png'};}
function showNotice(){clearTimeout(autoTimer);const n=notice;if(!n)return;let title='',text='',art='';if(n.type==='answer'){const r=RES[n.resource];title=n.correct?'Ressource récupérée !':'Pas cette fois';text=n.correct?`${icon(n.resource)} <b>+1 ${esc(r.name.toLowerCase())}</b> dans le sac ${esc(withDe(game.players[n.player].name))}.`:'La ressource reste sur la planète. Le voyage continue.';art=n.correct?`media/events/P_${r.code}.png`:'media/img/Navette.webp?v=12';}if(n.type==='deposit'){title='Ravitaillement effectué !';const gains=KEYS.filter(k=>n.deposited[k]>0);text=gains.length?'<span class="deposit-summary">'+gains.map(k=>`<span>${icon(k)} <b>+${n.deposited[k]}</b></span>`).join('')+'</span>':'';art='media/img/Rocket70.png';}if(n.type==='event'){const t=eventText(n.event);title=t.title;text=t.text;art=t.image;}if(n.type==='next'){title=`${esc(game.players[game.active].name)}, à toi !`;art='media/img/Rocket70.png';}if(n.type==='won'){showVictory();return;}modal(`<img class="notice-art" src="${esc(art)}" alt=""><h2 class="notice-title ${n.type==='answer'&&n.correct?'feedback-ok':''}">${title}</h2>${text?`<p class="notice-text">${text}</p>`:''}<div class="modal-actions" style="justify-content:center">${button(n.type==='next'?'Lancer le dé':'Continuer',n.type==='next'?'roll':'continue','primary')}</div>`,n.type==='deposit'?'centered deposit-modal':'centered');saveGame();}
function continueNotice(){closeModal();const previous=game.position;if(game.phase!=='arrive')game.continue();if(game.phase==='arrive'){notice=null;renderGame();if(game.position!==previous)playEffect('shuttle');saveGame();scheduleArrival();return;}notice={type:'next',player:game.active};renderGame();saveGame();showNotice();}
function pause(){if(!game)return;paused=true;shuttleMotion?.setPaused(true);clearTimeout(autoTimer);stopDieAnimation();if(depositView)finishDeposit(false);stopAudio();saveGame();modal(`<p class="eyebrow">Options enseignant · Partie en pause</p><h2>${esc(config.title)}</h2><p>${Math.floor(game.elapsed/60)} min ${Math.floor(game.elapsed%60)} s écoulées · durée cible : ${config.duration} min</p><table class="summary"><thead><tr><th>Joueur</th><th>Dé</th><th>Questions</th><th>Réussites</th><th>Aides</th></tr></thead><tbody>${game.players.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.rolls}</td><td>${p.questions}</td><td>${p.successes}</td><td>${p.helps}</td></tr>`).join('')}</tbody></table><div class="modal-actions">${button('Exporter le bilan','report','secondary')}${button('Retour à la préparation','to-setup','secondary')}${button('Reprendre','unpause','primary')}</div>`,'wide');}
function showPhase(){if(game.missionStarted===false){showMissionGate();return;}if(game.phase==='die')showDie(false);else if(game.phase==='roll'&&notice?.type==='next')showNotice();else if(game.phase==='resource')showResources();else if(game.phase==='question')showQuestion();else if(game.phase==='notice')showNotice();else if(game.phase==='won')showVictory();else if(game.phase==='arrive'){if(notice?.type==='event')showNotice();else scheduleArrival();}}

function resume(){const saved=readLocal(GAME_KEY);try{if(saved?.version!==2)throw Error('Sauvegarde incompatible.');game=E.Game.restore(saved.snapshot);E.validate(game.config);config=game.config;notice=saved.notice;paused=true;const selected=game,pending=prepareAssets(),ready=()=>{if(game!==selected)return;paused=false;lastTick=Date.now();closeModal();renderGame();showPhase();saveGame();};if(pending){modal('<p role="status">Chargement de la mission…</p>','mission-gate centered');pending.then(ready);}else ready();}catch(e){toast('La partie ne peut pas être reprise : '+e.message);game=null;}}

function showVictory(){stopAudio();modal(`<img class="notice-art rocket launch" src="media/img/Rocket70.png" alt="La fusée décolle"><p class="eyebrow">Mission accomplie</p><h2 class="notice-title">Vous avez réussi ensemble !</h2><p class="notice-text">La fusée est ravitaillée.<br>L’équipage peut décoller !</p><div class="modal-actions" style="justify-content:center">${button('Voir le bilan','pause','secondary')}${button('Nouvelle mission','to-setup','primary')}</div>`,'centered');saveGame();}
async function importFile(el){const file=el.files?.[0];if(!file)return;try{if(el.dataset.file==='config'){if(file.size>15e6)throw Error('Ce fichier est trop volumineux.');const next=JSON.parse(await file.text());if(next.version!==2)throw Error('Version de préparation non reconnue.');E.validate(next,true);config=next;refreshActivitySnapshots(false);saveConfig();error='';setup();toast('Préparation importée.');}}catch(e){toast(e.message);}el.value='';}
function setActivity(resource,id){const record=teacherActivities.find(a=>String(a.id)===String(id));if(!record){config.activities[resource]=null;return;}const previous=config.activities[resource],level=String(previous?.id||'')===String(record.id)?Number(previous?.level||3):3;config.activities[resource]={id:String(record.id),title:String(record.title||'Activité'),level,snapshot:clone(record)};}
function refreshActivitySnapshots(persist=true){if(!config.activities||typeof config.activities!=='object')config.activities=Object.fromEntries(KEYS.map(k=>[k,null]));for(const k of KEYS){const current=config.activities[k];if(!current?.id)continue;const fresh=teacherActivities.find(a=>String(a.id)===String(current.id));if(fresh){current.title=String(fresh.title||current.title||'Activité');current.snapshot=clone(fresh);if(String(fresh.difficulty_mode||'single')!=='adaptive')current.level=3;}}if(persist)saveConfig();}
document.addEventListener('change',e=>{const el=e.target;if(el.matches('[data-file]')){importFile(el);return;}if(el.id==='player-count'){const n=Number(el.value);while(config.players.length<n)config.players.push('Astronaute '+(config.players.length+1));config.players.length=n;saveConfig();setup();return;}if(el.dataset.player!==undefined){config.players[Number(el.dataset.player)]=el.value.trim();saveConfig();drawMini();}if(el.id==='duration'||el.id==='dust'){config[el.id]=Number(el.value);saveConfig();}if(el.dataset.target){config.targets[el.dataset.target]=Number(el.value);saveConfig();}if(el.id==='mission-title'){config.title=el.value;saveConfig();}if(el.id==='activity-select'){setActivity(el.dataset.resource,el.value);saveConfig();setup();return;}if(el.id==='activity-level'){const a=config.activities?.[el.dataset.resource];if(a){a.level=Math.max(1,Math.min(5,Number(el.value)||3));saveConfig();setup();return;}}const summary=document.getElementById('mission-summary');if(summary)summary.textContent=config.players.length+' astronautes · '+KEYS.reduce((sum,k)=>sum+config.targets[k],0)+' ressources à déposer';});
document.addEventListener('pointerup',restoreGameFullscreen,true);
document.addEventListener('click',e=>{restoreGameFullscreen();if(!paused&&game?.phase==='die'&&dieReady&&document.getElementById('die-confirm')){e.preventDefault();e.stopImmediatePropagation();acceptDie();}},true);
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action;try{if(a==='tab-mission'||a==='tab-activities'){tab=a.slice(4);error='';setup();}else if(a.startsWith('activity-')){activityResource=a.slice(9);setup();}else if(a==='export')download('fusee-preparation-tujer.json',config);else if(a==='start')start();else if(a==='confirm-start')start.begin();else if(a==='launch-mission')launchMission();else if(a==='resume')resume();else if(a==='close'){stopAudio();closeModal();}else if(a==='roll')rollDie();else if(a==='accept-die')acceptDie();else if(a==='move'){if(paused||depositView||game.phase!=='move')return;game.move(el.dataset.node);renderBoard();playEffect('shuttle');saveGame();if(game.phase==='arrive'){scheduleArrival();}}else if(a.startsWith('resource-')){game.questionFor(a.slice(9));notice=null;showQuestion();}else if(a==='continue')continueNotice();else if(a==='sound'){sound=!sound;if(!sound)stopAudio();renderGame();}else if(a==='fullscreen'){enterFullscreen();}else if(a==='pause'){if(game?.phase!=='question')pause();}else if(a==='unpause'){paused=false;lastTick=Date.now();closeModal();renderGame();showPhase();}else if(a==='report')download('fusee-bilan.json',{mission:config.title,targetMinutes:config.duration,elapsedSeconds:Math.round(game.elapsed),players:game.players,stock:game.stock,events:game.log});else if(a==='to-setup'){paused=true;if(depositView)finishDeposit(false);stopAudio();clearTimeout(autoTimer);stopDieAnimation();saveGame();game=null;notice=null;tab='mission';setup();}}catch(err){toast(err.message);}});
document.addEventListener('contextmenu',e=>{if(game)e.preventDefault();});
document.addEventListener('selectstart',e=>{if(game&&!e.target.closest?.('input,textarea,[contenteditable=true]'))e.preventDefault();});
document.addEventListener('dragstart',e=>{if(game)e.preventDefault();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&game&&!paused&&game.phase!=='question'){e.preventDefault();pause();}const dialog=document.querySelector('.modal:not(.question-modal)');if(e.key==='Tab'&&dialog){const items=[...dialog.querySelectorAll('button:not(:disabled),input:not([type=file]),select,textarea,summary')].filter(x=>!x.closest('[hidden]'));if(items.length){if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0].focus();}}}});
document.addEventListener('visibilitychange',()=>{lastTick=Date.now();if(document.hidden){if(depositView)finishDeposit();stopAudio();saveGame();}});window.addEventListener('beforeunload',()=>saveGame());setInterval(()=>{const now=Date.now();if(game&&!paused&&!document.hidden&&game.phase!=='won'&&game.missionStarted!==false){game.elapsed+=Math.min(5,(now-lastTick)/1000);if(Math.floor(game.elapsed)%10===0)saveGame();}lastTick=now;},1000);
window.addEventListener('resize',()=>{if(game)renderBoard();});
window.FuseeApp={getConfig:()=>clone(config),getGame:()=>game,setConfig:next=>{if(game)throw Error('Quitte la partie avant de modifier la préparation.');E.validate(next,true);config=clone(next);saveConfig();setup();prepareAssets();},start,resume};
async function loadTujerActivities(){const user=await getCurrentUser();if(!user){window.location.href='../../teacher/login.html';return false;}teacherSpace=await getMyTeacherSpace();if(!teacherSpace)throw Error('Espace enseignant introuvable.');teacherActivities=await listTeacherActivitiesForSpace(teacherSpace.id);refreshActivitySnapshots(false);return true;}
async function init(){try{await loadTujerActivities();}catch(err){error='Impossible de charger « Mes activités » : '+(err?.message||err);teacherActivities=[];}if(window.indexedDB){try{stateDB=await new Promise((resolve,reject)=>{const request=indexedDB.open('fusee-tujer-v2',1);request.onupgradeneeded=()=>request.result.createObjectStore('state');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});await Promise.all([CONFIG_KEY,GAME_KEY].map(key=>new Promise(resolve=>{const request=stateDB.transaction('state').objectStore('state').get(key);request.onsuccess=()=>{if(request.result){try{stateCache.set(key,JSON.parse(request.result));}catch{}}resolve();};request.onerror=()=>resolve();})));const saved=readLocal(CONFIG_KEY);if(saved){E.validate(saved,true);config=saved;refreshActivitySnapshots(false);}}catch{stateDB=null;}}setup();prepareAssets();}
init();
})();
