/* Moteur autonome : aucun accès au DOM, aucune dépendance Tujer. */
(function(root){
'use strict';
const KEYS=['carburant','eau','provisions','outils','oxygene'];
const PLANETS=[
 {id:'p0',key:'eau',resource:'eau',name:'Eau',asset:'Pla1.png'},
 {id:'p1',key:'oxygene',resource:'oxygene',name:'Oxygène',asset:'Pla2.png'},
 {id:'p2',key:'carburant',resource:'carburant',name:'Carburant',asset:'Pla3.png'},
 {id:'p3',key:'provisions',resource:'provisions',name:'Provisions',asset:'Pla4.png'},
 {id:'p4',key:'merchant',merchant:true,name:'Marchand',asset:'Pla5.png'},
 {id:'p5',key:'outils',resource:'outils',name:'Outils',asset:'Pla6.png'}
];
const TRANSPORT_STORIES=14;
const DIE_FACES=['rocket',2,3,4,5,'asteroid'];
const empty=()=>Object.fromEntries(KEYS.map(k=>[k,0]));
const weighted=(items,rng=Math.random)=>{let sum=items.reduce((s,x)=>s+Math.max(0,Number(x.weight)||0),0);if(sum<=0)return items[0]?.value;let t=rng()*sum;for(const x of items){t-=Math.max(0,Number(x.weight)||0);if(t<0)return x.value;}return items.at(-1)?.value;};
const planetById=id=>PLANETS.find(p=>p.id===id)||null;
function board(){const n=PLANETS.length,nodes={},edges=[];function add(id,type,a,r,extra={}){nodes[id]={id,type,x:50+43*r*Math.cos(a),y:50+40*r*Math.sin(a),neighbors:[],...extra};}function link(a,b){nodes[a].neighbors.push(b);nodes[b].neighbors.push(a);edges.push([a,b]);}add('c','center',0,0);for(let i=0;i<n;i++){const a=-Math.PI/2+2*Math.PI*i/n,planet=PLANETS[i];add('p'+i,'planet',a,1,{planetIndex:i,planetKey:planet.key,resource:planet.resource||null,merchant:planet.merchant===true});for(let j=1;j<=2;j++)add(`b${i}_${j}`,'neutral',a,j/3);link('c',`b${i}_1`);link(`b${i}_1`,`b${i}_2`);link(`b${i}_2`,'p'+i);for(let j=1;j<=3;j++)add(`r${i}_${j}`,j===2?'asteroid':'neutral',a+2*Math.PI/n*j/4,1);}for(let i=0;i<n;i++){link('p'+i,`r${i}_1`);link(`r${i}_1`,`r${i}_2`);link(`r${i}_2`,`r${i}_3`);link(`r${i}_3`,'p'+((i+1)%n));}return {nodes,edges};}

// Un même germe donne le même plateau, y compris après une reprise.
function createLayout(_n,seed,width=1000,height=560,attempt=0){
 const b=board(),n=PLANETS.length;let state=seed>>>0;const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};
 const marginX=66,marginY=66,bottom=86,innerW=width-2*marginX,innerH=height-marginY-bottom;
 const perimeter=t=>{const s=(4*t+.5)%4;return s<1?[s,0]:s<2?[1,s-1]:s<3?[3-s,1]:[0,4-s];};
 const points={},jitter=(v,amount)=>v+(random()-.5)*2*amount;
 const add=(id,x,y)=>points[id]={x,y,r:b.nodes[id].type==='center'?112:b.nodes[id].type==='planet'?58:b.nodes[id].type==='asteroid'?33:24};
 add('c',width/2,height/2);
 for(let i=0;i<n;i++){
  const uv=perimeter(i/n),x=marginX+uv[0]*innerW,y=marginY+uv[1]*innerH;
  add('p'+i,jitter(x,42),jitter(y,42));
  for(let j=1;j<=2;j++)add(`b${i}_${j}`,jitter(width/2+(x-width/2)*j/3,48),jitter(height/2+(y-height/2)*j/3,48));
  for(let j=1;j<=3;j++){const v=perimeter((i+j/4)/n);add(`r${i}_${j}`,jitter(marginX+v[0]*innerW,42),jitter(marginY+v[1]*innerH,42));}
 }
 const ids=Object.keys(points),clamp=p=>{p.x=Math.max(marginX,Math.min(width-marginX,p.x));p.y=Math.max(marginY,Math.min(height-bottom,p.y));};
 for(let pass=0;pass<1800;pass++){
  let overlap=0;
  if(pass>0&&pass%150===0)for(const id of ids)if(id!=='c'){points[id].x=jitter(points[id].x,8);points[id].y=jitter(points[id].y,8);clamp(points[id]);}
  for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){
   const a=points[ids[i]],c=points[ids[j]],dx=c.x-a.x,dy=c.y-a.y,d=Math.hypot(dx,dy),min=a.r+c.r+22;
   if(d>=min)continue;overlap=Math.max(overlap,min-d);
   const ux=d?dx/d:1,uy=d?dy/d:0,shift=(min-d+.05)/(ids[i]==='c'||ids[j]==='c'?1:2);
   if(ids[i]!=='c'){a.x-=ux*shift;a.y-=uy*shift;clamp(a);}
   if(ids[j]!=='c'){c.x+=ux*shift;c.y+=uy*shift;clamp(c);}
  }
  for(const id of ids)if(id!=='c')clamp(points[id]);
  if(overlap<.1)break;
 }
 let unresolved=0;for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const a=points[ids[i]],c=points[ids[j]];unresolved=Math.max(unresolved,a.r+c.r+22-Math.hypot(c.x-a.x,c.y-a.y));}
 if(unresolved>.5&&attempt<24)return createLayout(n,(seed+2654435761)>>>0,width,height,attempt+1);
 return Object.fromEntries(ids.map(id=>[id,{x:points[id].x/width*100,y:points[id].y/height*100}]));
}

function validate(c,draft=false){if(!c||!Array.isArray(c.players)||c.players.length<2||c.players.length>8)throw Error('Choisis de 2 à 8 joueurs.');if(c.players.some(x=>typeof x!=='string'||!x.trim()||x.length>24))throw Error('Chaque joueur doit avoir un prénom (24 caractères maximum).');if(!Number.isFinite(c.duration)||c.duration<5||c.duration>120)throw Error('La durée doit être comprise entre 5 et 120 minutes.');if(!Number.isInteger(c.dust)||c.dust<0||c.dust>30)throw Error('La poussière doit être comprise entre 0 et 30.');if(!KEYS.every(k=>Number.isInteger(c.targets?.[k])&&c.targets[k]>=0&&c.targets[k]<=50)||(!draft&&!KEYS.some(k=>c.targets[k]>0)))throw Error('Prévois au moins une ressource (0 à 50 de chaque).');for(const k of KEYS){const assignment=c.activities?.[k];if(!draft&&c.targets[k]>0&&!assignment?.snapshot?.config_json?.tool_id)throw Error('Choisis une activité Tujer pour la ressource : '+k);if(assignment){if(!assignment.snapshot||typeof assignment.snapshot!=='object')throw Error('Configuration d’activité invalide : '+k);if(!String(assignment.snapshot?.config_json?.tool_id||'').trim())throw Error('Cette activité Tujer ne peut pas être lancée : '+k);const level=Math.trunc(Number(assignment.level)||3);if(level<1||level>5)throw Error('Le niveau de l’activité doit être compris entre 1 et 5.');}}return true;}
class Game{
constructor(config,rng=Math.random){validate(config);this.config=JSON.parse(JSON.stringify(config));this.rng=rng;this.boardVersion=2;this.board=board();this.layoutSeed=(Math.random()*4294967296)>>>0;this.layout=null;this.arrivalKind=null;this.nextTurnReady=false;this.players=config.players.map(name=>({name,bag:empty(),rolls:0,questions:0,successes:0,helps:0}));this.stock=empty();this.active=0;this.position='c';this.dust=config.dust;this.phase='roll';this.remaining=0;this.visited=[];this.turn=0;this.consecutiveRolls=0;this.rollsSinceQuestion=0;this.blocked={};this.elapsed=0;this.log=[];this.question=null;this.questionCheckpoint=null;this.helpUsed=false;this.lastEvent=null;this.pendingTravel=null;this.pendingResource=null;this.pendingQuestionPlayer=null;this.pendingQuestionReason=null;this.pendingPlanet=null;this.pendingMerchant=false;this.pendingQuestionEvent=null;this.pendingQuestionResumePhase=null;this.answerResumePhase=null;}
record(type,data={}){this.log.push({time:Math.round(this.elapsed),type,...data});}
roll(){if(this.phase!=='roll')throw Error('Le dé n’est pas disponible.');this.turn++;for(const id of Object.keys(this.blocked))if(this.blocked[id]<=this.turn)delete this.blocked[id];this.players[this.active].rolls++;this.consecutiveRolls++;this.rollsSinceQuestion++;const outcomes=DIE_FACES.filter(d=>(d!=='rocket'||(this.position!=='c'&&this.die!=='rocket'))&&(typeof d!=='number'||this.canFinish(this.position,d,[this.position]))),numeric=outcomes.filter(d=>typeof d==='number'),withKinds=numeric.map(d=>({die:d,kinds:this.arrivalKinds(d)})),both=withKinds.filter(x=>x.kinds.has('planet')&&x.kinds.has('asteroid')).map(x=>x.die),either=withKinds.filter(x=>x.kinds.has('planet')||x.kinds.has('asteroid')).map(x=>x.die);let pool=outcomes,policy='random';if(this.rollsSinceQuestion===2){if(both.length){pool=both;policy='cadence-both';}else if(either.length){pool=either;policy='cadence-either';}}else if(this.rollsSinceQuestion>=3){if(both.length){pool=both;policy='cadence-both';}else if(outcomes.includes('asteroid')){pool=['asteroid'];policy='cadence-event';}}this.die=pool[Math.floor(this.rng()*pool.length)];this.remaining=0;this.phase='die';this.arrivalKind=null;this.nextTurnReady=false;this.record('roll',{player:this.active,die:this.die,rollsSinceQuestion:this.rollsSinceQuestion,policy});return this.die;}
acceptRoll(){if(this.phase!=='die')throw Error('Aucun dé à valider.');this.remaining=typeof this.die==='number'?this.die:0;this.visited=[this.position];this.arrivalKind=this.die==='asteroid'?'asteroid':null;if(this.die==='rocket')this.position='c';this.phase=this.remaining?'move':'arrive';this.record('acceptRoll',{die:this.die});return this.phase;}
canFinish(id,steps,seen){if(!steps)return true;return this.board.nodes[id].neighbors.some(next=>!seen.includes(next)&&!this.blocked[next]&&this.canFinish(next,steps-1,[...seen,next]));}
arrivalNodes(steps){const destinations=new Set(),walk=(id,left,seen)=>{if(!left){destinations.add(id);return;}for(const next of this.board.nodes[id].neighbors){if(seen.includes(next)||this.blocked[next])continue;if(next==='c'){destinations.add(next);continue;}walk(next,left-1,[...seen,next]);}};walk(this.position,steps,[this.position]);return [...destinations];}
arrivalKinds(steps){return new Set(this.arrivalNodes(steps).map(id=>this.board.nodes[id]?.type).filter(Boolean));}
options(){if(this.phase!=='move')return [];return this.board.nodes[this.position].neighbors.filter(id=>!this.visited.includes(id)&&!this.blocked[id]&&this.canFinish(id,this.remaining-1,[...this.visited,id]));}
move(id){if(!this.options().includes(id))throw Error('Cette case n’est pas accessible.');this.position=id;this.visited.push(id);this.remaining--;if(!this.remaining||this.board.nodes[id].type==='center')this.phase='arrive';this.record('move',{node:id});}
resourceState(k){const target=this.config.targets[k]||0,carried=this.players.reduce((s,p)=>s+(p.bag[k]||0),0),secured=(this.stock[k]||0)+carried,missing=Math.max(0,target-secured);return {key:k,target,carried,secured,missing,ratio:target?missing/target:0};}
usableResources(){return KEYS.filter(k=>this.config.targets[k]>0&&this.config.activities?.[k]?.snapshot?.config_json?.tool_id);}
pickQuestionResource(preferred=null){const usable=this.usableResources();if(preferred&&usable.includes(preferred))return preferred;if(!usable.length)return null;const states=usable.map(k=>this.resourceState(k)),maxRatio=Math.max(...states.map(s=>s.ratio)),best=states.filter(s=>Math.abs(s.ratio-maxRatio)<1e-9);if(maxRatio<=0){const minStock=Math.min(...states.map(s=>this.stock[s.key]||0));return weighted(states.filter(s=>(this.stock[s.key]||0)===minStock).map(s=>({value:s.key,weight:1})),this.rng);}return weighted(best.map(s=>({value:s.key,weight:Math.max(1,s.missing)})),this.rng);}
pickMerchantResource(){return this.pickQuestionResource();}
pickQuestionPlayer(){return this.active;}
prepareQuestion(resource,{reason='planet',planet=null,merchant=false,resumePhase=null}={}){const selected=this.pickQuestionResource(resource);if(!selected)return false;this.pendingResource=selected;this.pendingQuestionPlayer=this.active;this.pendingQuestionReason=reason;this.pendingPlanet=planet;this.pendingMerchant=merchant===true;this.pendingQuestionResumePhase=resumePhase||null;this.phase='resource';this.nextTurnReady=false;return true;}
resolve(){if(this.phase!=='arrive')throw Error('Déplacement inachevé.');const node=this.arrivalKind?{type:this.arrivalKind}:this.board.nodes[this.position];this.arrivalKind=null;if(node.type==='planet'){const planet=planetById(node.id),resource=planet?.merchant?this.pickMerchantResource():this.pickQuestionResource(planet?.resource);if(this.prepareQuestion(resource,{reason:'planet',planet:node.id,merchant:planet?.merchant===true}))return {type:'planet',planet:node.id,resource:this.pendingResource,merchant:this.pendingMerchant,player:this.pendingQuestionPlayer};this.nextTurnReady=true;this.phase='notice';return {type:'next',player:this.active};}if(node.type==='center'){let deposited=empty();for(const p of this.players)for(const k of KEYS){deposited[k]+=p.bag[k];this.stock[k]+=p.bag[k];p.bag[k]=0;}const won=KEYS.every(k=>this.stock[k]>=this.config.targets[k]);this.phase=won?'won':'notice';this.record('deposit',{deposited,won});return {type:won?'won':'deposit',deposited};}if(node.type==='asteroid'){if(this.rollsSinceQuestion>=2){const resource=this.pickQuestionResource();if(this.prepareQuestion(resource,{reason:'cadence'}))return {type:'questionEvent',resource:this.pendingResource,player:this.pendingQuestionPlayer,reason:'cadence'};}const event=this.pickEvent();if(event.kind==='challenge'){if(this.prepareQuestion(event.resource,{reason:'event'}))return {type:'questionEvent',resource:this.pendingResource,player:this.pendingQuestionPlayer,reason:'event'};}this.phase='notice';this.applyEvent(event);return {type:'event',event};}this.nextTurnReady=true;this.phase='notice';return {type:'next',player:this.active};}
setActivePlayer(player){if(player!==this.active)this.consecutiveRolls=0;this.active=player;}
nextPlayer(exclude=this.active){const ids=this.players.map((p,i)=>({i,p})).filter(x=>x.i!==exclude);const min=Math.min(...ids.map(x=>x.p.questions));return weighted(ids.filter(x=>x.p.questions===min).map(x=>({value:x.i,weight:1})),this.rng);}
continue(){if(this.phase!=='notice')throw Error('Impossible de continuer.');if(this.pendingQuestionEvent){const pending=this.pendingQuestionEvent;this.pendingQuestionEvent=null;if(this.prepareQuestion(pending.resource,{reason:pending.reason||'cadence',resumePhase:pending.resumePhase||null}))return this.active;}if(this.answerResumePhase){const phase=this.answerResumePhase;this.answerResumePhase=null;this.phase=phase;return this.active;}if(this.pendingTravel){this.position=this.pendingTravel;this.pendingTravel=null;this.phase='arrive';return this.active;}if(this.position==='c'&&this.remaining>0){this.phase='move';return this.active;}this.nextTurnReady=false;this.phase='roll';return this.active;}
questionFor(k){const assignment=this.config.activities?.[k];if(this.phase!=='resource'||!KEYS.includes(k)||!assignment?.snapshot?.config_json?.tool_id||!this.config.targets[k])throw Error('Ressource indisponible.');const player=this.active;this.question={resource:k,activity:JSON.parse(JSON.stringify(assignment)),player,reason:this.pendingQuestionReason||'planet',planet:this.pendingPlanet||null,merchant:this.pendingMerchant===true,resumePhase:this.pendingQuestionResumePhase||null};this.pendingResource=null;this.pendingQuestionPlayer=null;this.pendingQuestionReason=null;this.pendingPlanet=null;this.pendingMerchant=false;this.pendingQuestionResumePhase=null;this.questionCheckpoint=null;this.helpUsed=false;this.nextTurnReady=false;this.players[player].questions++;this.rollsSinceQuestion=0;this.phase='question';this.record('question',{player,resource:k,reason:this.question.reason,activityId:String(assignment.id||''),activityTitle:String(assignment.title||assignment.snapshot?.title||'')});return this.question;}
help(i){const player=Number.isInteger(this.question?.player)?this.question.player:this.active;if(this.phase!=='question'||this.helpUsed||this.dust<1||i===player||!this.players[i])throw Error('Aide indisponible.');this.dust--;this.helpUsed=true;this.players[i].helps++;this.record('help',{player,helper:i});}
resolveQuestion(correct){if(this.phase!=='question')throw Error('Pas de question en cours.');const success=correct===true,resource=this.question?.resource,player=Number.isInteger(this.question?.player)?this.question.player:this.active,resumePhase=this.question?.resumePhase||null;if(success&&resource){this.players[player].bag[resource]++;this.players[player].successes++;}this.questionCheckpoint=null;this.answerResumePhase=resumePhase;this.phase='notice';this.nextTurnReady=!resumePhase;this.record('answer',{player,resource,correct:success});this.setActivePlayer(this.nextPlayer(player));return success;}
progress(){let total=0,loaded=0;for(const k of KEYS){total+=this.config.targets[k];loaded+=Math.min(this.config.targets[k],this.stock[k]+.6*this.players.reduce((s,p)=>s+p.bag[k],0));}return total?loaded/total:1;}
pickPlanetDestination(){const candidates=PLANETS.filter(p=>!this.blocked[p.id]&&p.id!==this.position);if(!candidates.length)return PLANETS.find(p=>!this.blocked[p.id])?.id||'p4';const states=Object.fromEntries(KEYS.map(k=>[k,this.resourceState(k)]));return weighted(candidates.map(p=>{let weight=1;if(p.merchant){const max=Math.max(...KEYS.map(k=>states[k].ratio));weight=1.4+5*max;}else{const s=states[p.resource];weight=.7+7*(s?.ratio||0)+.3*(s?.missing||0);}return {value:p.id,weight};}),this.rng);}
pickBlockPlanet(){const candidates=PLANETS.filter(p=>!this.blocked[p.id]&&!p.merchant);if(!candidates.length)return null;return weighted(candidates.map(p=>{const s=this.resourceState(p.resource);const completion=s.target?1-s.ratio:1;return {value:p.id,weight:.5+4*completion};}),this.rng);}
pickEvent(){const expected=Math.min(1.2,this.elapsed/(this.config.duration*60)),gap=expected-this.progress(),boost=Math.exp(Math.max(-3,Math.min(3,gap*7))),late=expected>.82,urgent=expected>.95&&this.progress()<.9;const events=[];for(const k of KEYS){if(!this.config.targets[k])continue;const carried=this.players.reduce((s,p)=>s+p.bag[k],0),missing=Math.max(0,this.config.targets[k]-this.stock[k]-carried);events.push({value:{kind:'gain',resource:k},weight:boost*(missing+1)*(late?2.5:1)});if(carried>0)events.push({value:{kind:'loss',resource:k},weight:(1/boost)*(late?.08:1)});}const challengeResource=this.pickQuestionResource();if(challengeResource)events.push({value:{kind:'challenge',resource:challengeResource},weight:(2.2+this.rollsSinceQuestion*2.4)*boost*(late?1.8:1)});events.push({value:{kind:'dustGain'},weight:1.1*boost});if(this.dust>0)events.push({value:{kind:'dustLoss'},weight:.45/boost});events.push({value:{kind:'calm'},weight:this.rollsSinceQuestion?0.35:0.7});const blockedIds=Object.keys(this.blocked);if(!blockedIds.length&&expected<.82){const planet=this.pickBlockPlanet();if(planet)events.push({value:{kind:'block',planet},weight:.65/boost});}if(blockedIds.length)events.push({value:{kind:'unblock'},weight:1.8*boost});if((late||urgent)&&KEYS.some(k=>this.players.some(p=>p.bag[k]>0)))events.push({value:{kind:'return'},weight:(urgent?12:5.5)*boost});const otherWeight=events.reduce((sum,x)=>sum+x.weight,0);events.push({value:{kind:'transport'},weight:otherWeight*(urgent?1.35:late?.85:1.45)});const event=weighted(events,this.rng);if(event.kind==='transport'){event.planet=this.pickPlanetDestination();event.story=Math.floor(this.rng()*TRANSPORT_STORIES);}return event;}
applyEvent(e){if(e.kind==='gain')this.players[this.active].bag[e.resource]++;if(e.kind==='loss'){const max=Math.max(...this.players.map(p=>p.bag[e.resource]));const i=this.players.findIndex(p=>p.bag[e.resource]===max);if(max>0){this.players[i].bag[e.resource]--;e.player=i;}}if(e.kind==='dustGain')this.dust++;if(e.kind==='dustLoss')this.dust=Math.max(0,this.dust-1);if(e.kind==='block'&&e.planet)this.blocked[e.planet]=this.turn+4;if(e.kind==='unblock')this.blocked={};if(e.kind==='return'){this.pendingTravel='c';this.phase='notice';}if(e.kind==='transport'){const id=e.planet||('p'+Number(e.player||0)%PLANETS.length);if(!this.board.nodes[id]||this.blocked[id])throw Error('Cette planète est inaccessible.');e.planet=id;this.pendingTravel=id;this.phase='notice';}this.lastEvent=e;this.record('event',e);}
snapshot(){const {rng,...data}=this;return JSON.parse(JSON.stringify(data));}
static restore(snapshot,rng=Math.random){const game=new Game(snapshot.config,rng),oldBoardVersion=snapshot.boardVersion;Object.assign(game,snapshot);game.rng=rng;game.boardVersion=2;game.board=board();const remapNode=id=>{if(typeof id!=='string'||game.board.nodes[id])return id;const m=id.match(/^([pbr])(\d+)(.*)$/);if(!m)return 'c';const mapped=m[1]+(Number(m[2])%PLANETS.length)+m[3];return game.board.nodes[mapped]?mapped:'c';};if(oldBoardVersion!==2){game.position=remapNode(game.position);game.visited=[...new Set((game.visited||[]).map(remapNode).filter(id=>game.board.nodes[id]))];game.pendingTravel=game.pendingTravel?remapNode(game.pendingTravel):null;const migratedBlocked={};for(const [id,until] of Object.entries(game.blocked||{})){const mapped=remapNode(id);if(mapped.startsWith('p'))migratedBlocked[mapped]=Math.max(migratedBlocked[mapped]||0,until);}game.blocked=migratedBlocked;game.layout=null;}if(!Number.isInteger(snapshot.consecutiveRolls)){game.consecutiveRolls=0;for(let i=game.log.length-1;i>=0;i--){const entry=game.log[i];if(entry.type!=='roll')continue;if(entry.player!==game.active)break;game.consecutiveRolls++;}if(game.phase==='notice'&&game.log.at(-1)?.type==='answer')game.nextTurnReady=true;}if(!Number.isInteger(snapshot.rollsSinceQuestion)){let count=0;for(let i=game.log.length-1;i>=0;i--){const entry=game.log[i];if(entry.type==='question')break;if(entry.type==='roll')count++;}game.rollsSinceQuestion=count;}if(game.pendingQuestionEvent?.reason==='cadence')game.pendingQuestionEvent=null;if(game.question&&!Number.isInteger(game.question.player))game.question.player=game.active;if(game.phase==='resource'&&!game.pendingResource){const planet=planetById(game.position),resource=planet?.merchant?game.pickMerchantResource():game.pickQuestionResource(planet?.resource);game.pendingResource=resource;game.pendingQuestionReason='planet';game.pendingPlanet=planet?.id||null;game.pendingMerchant=planet?.merchant===true;}if(game.phase==='resource')game.pendingQuestionPlayer=game.active;return game;}
}
const api={Game,board,createLayout,validate,KEYS,PLANETS,DIE_FACES,TRANSPORT_STORIES,weighted};if(typeof module!=='undefined')module.exports=api;root.FuseeEngine=api;
})(typeof window==='undefined'?globalThis:window);
